// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncbrcytyuvftzrqonnzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jYnJjeXR5dXZmdHpycW9ubnpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDkxMjgsImV4cCI6MjA1OTIyNTEyOH0.i87WXXKNPDjQllcjgWxclst1dy9--47WvChGiH-vj9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);